name = "proxies"
type = "webpack"
zone_id = ""
account_id = ""
workers_dev = true
vars = { DOMAIN = "", UPDATE_CACHE_URL="" }
kv_namespaces = [ 
  { binding = "ProxiesCache", id = "", preview_id = "" }
]